trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# -------------------------
# Node.js
# -------------------------
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# -------------------------
# Install dependencies
# -------------------------
- script: |
    cd app
    npm ci
  displayName: 'Install dependencies'

# -------------------------
# Test application
# -------------------------
- script: |
    cd app
    npm start &
    sleep 5
    curl http://localhost:8080/health
  displayName: 'Test application'

# -------------------------
# Docker Build & Push
# -------------------------
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'acr-docker-connection'
    repository: 'devops-calculator'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

# -------------------------
# Terraform
# -------------------------
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.9.8'

- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

- task: TerraformTaskV4@4
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceNameAzureRM: 'azure-terraform-connection'