trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# -------------------------
# Node.js
# -------------------------
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# -------------------------
# Install dependencies
# -------------------------
- script: |
    cd app
    npm ci
  displayName: 'Install dependencies'

# -------------------------
# Test application
# -------------------------
- script: |
    cd app
    npm start &
    sleep 5
    curl http://localhost:8080/health
  displayName: 'Test application'

# -------------------------
# Docker Build & Push
# -------------------------
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'acr-docker-connection'
    repository: 'devops-calculator'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
# -------------------------
# Terraform
# -------------------------
- bash: |
    set -e

    TERRAFORM_VERSION="1.9.8"
    TEMP_DIR=$(mktemp -d)

    echo "Installing Terraform ${TERRAFORM_VERSION}..."
    echo "Temporary directory: ${TEMP_DIR}"

    cd "${TEMP_DIR}"

    wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

    unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip

    sudo install -m 0755 terraform /usr/local/bin/terraform

    terraform version

    rm -rf "${TEMP_DIR}"
  displayName: 'Install Terraform'

- task: AzureCLI@2
  displayName: 'Terraform Init'
  inputs:
    azureSubscription: 'azure-terraform-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd terraform
      terraform init -upgrade

- task: AzureCLI@2
  displayName: 'Terraform Validate'
  inputs:
    azureSubscription: 'azure-terraform-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd terraform
      terraform validate

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'azure-terraform-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd terraform
      terraform plan

- task: AzureCLI@2
  displayName: 'Terraform Apply'
  inputs:
    azureSubscription: 'azure-terraform-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd terraform
      terraform apply -auto-approve